ruby-projects/RAILS-01/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get "about" , to: "about#index"

  get "/", to: "main#index"
  get "/sign_up", to: "registrations#new"
  post "/sign_up",   to: "registrations#create"
end

ruby-projects/RAILS-01/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

ruby-projects/RAILS-01/app/models/user.rb
class User < ApplicationRecord
    has_secure_password 
    validates :email, presence: true 
    
end

ruby-projects/RAILS-01/app/controllers/about_controller.rb
class AboutController < ApplicationController 
    def index 
    end
end

ruby-projects/RAILS-01/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

ruby-projects/RAILS-01/app/controllers/main_controller.rb
class MainController < ApplicationController
    def index 
        flash.now[:notice] = "logged in successfullly"
    end
end

ruby-projects/RAILS-01/app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController 
    def new 
        @user = User.new
    end
    def create 
        render plain: "Thanks!"
    end
 end

ruby-projects/RAILS-01/app/helpers/application_helper.rb
module ApplicationHelper
end

ruby-projects/RAILS-01/app/views/about/index.erb
<h1> about us </h1>

ruby-projects/RAILS-01/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>


    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= render partial: "shared/navbar" %>
  <div class="container">
    <%= render partial: "shared/flash" %>
    <%= yield %>
  </body>
  </div>
</html>

ruby-projects/RAILS-01/app/views/main/index.erb
<div class="d-flex align-items-center justify-content-center ">
<h1> welcome to rails development environment</h1>
</div>

ruby-projects/RAILS-01/app/views/shared/_flash.erb
<% if flash[:notice] %>
<div class="alert alert-info mt-4" role="alert" > 
<%= flash[:notice] %>
</div>
<% end %>

ruby-projects/RAILS-01/app/views/shared/_navbar.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/">Home</a>
        </li>
        <li class="nav-item">

          <!--- <a class="nav-link" href="/about">About</a> --->
          <%= link_to "About", about_path, class: "nav-link" %>
        </li>
        <li class="nav-item">

        <!--- <a class="nav-link" href="/sign_up">Sign Up</a> --->
        <%= link_to "Sign Up", sign_up_path, class: "nav-link" %>
      </li>


 
      </ul>
    </div>
  </div>
</nav>